name: Test

on: 
  pull_request:
    types: [labeled]

jobs:
  build:
    if: startsWith(toJSON(github.event.pull_request.labels),'test:')
    name: Hello
    runs-on: ubuntu-latest
    steps:
    - name: Hello World
      run: echo toJSON(github.event.pull_request.labels).split('test:')[1]